-- MySQL Script generated by MySQL Workbench
-- seg 14 ago 2017 20:44:34 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGPARCAT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGPARCAT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGPARCAT` DEFAULT CHARACTER SET utf8 ;
USE `SGPARCAT` ;

-- -----------------------------------------------------
-- Table `SGPARCAT`.`funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`funcao` (
  `idFuncao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`pessoa` (
  `idPessoa` BIGINT NOT NULL,
  `tipoPessoa` VARCHAR(25) NOT NULL,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `estadoCivil` CHAR(1) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(25) NOT NULL,
  `rg` VARCHAR(25) NULL,
  `isDizimista` TINYINT(1) NOT NULL,
  `isDizimistaAtivo` TINYINT(1) NOT NULL,
  `telefoneFixo` VARCHAR(20) NULL,
  `telefoneCelular` VARCHAR(20) NULL,
  `idFuncao` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_pessoa_funcao1_idx` (`idFuncao` ASC),
  CONSTRAINT `fk_pessoa_funcao1`
    FOREIGN KEY (`idFuncao`)
    REFERENCES `SGPARCAT`.`funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`contribuicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`contribuicao` (
  `numeroContribuicao` BIGINT NOT NULL AUTO_INCREMENT,
  `idPessoaContribuinte` BIGINT NULL,
  `tipoContribuicao` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(60) NOT NULL,
  `valor` DECIMAL(10,2) NULL,
  `dataRegistro` DATETIME NOT NULL,
  `observacao` VARCHAR(100) NULL,
  `idPessoaRegistrouContribuicao` BIGINT NOT NULL,
  PRIMARY KEY (`numeroContribuicao`),
  INDEX `fk_contribuicao_paroquiano1_idx` (`idPessoaContribuinte` ASC),
  INDEX `fk_contribuicao_pessoa1_idx` (`idPessoaRegistrouContribuicao` ASC),
  CONSTRAINT `fk_contribuicao_paroquiano1`
    FOREIGN KEY (`idPessoaContribuinte`)
    REFERENCES `SGPARCAT`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contribuicao_pessoa1`
    FOREIGN KEY (`idPessoaRegistrouContribuicao`)
    REFERENCES `SGPARCAT`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `horarioInicio` TIME NOT NULL,
  `dataFim` DATE NULL,
  `horarioFim` TIME NULL,
  `local` VARCHAR(45) NOT NULL,
  `observacao` TEXT NULL,
  `dataRegistro` DATETIME NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`lancamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`lancamento` (
  `idLancamento` BIGINT NOT NULL AUTO_INCREMENT,
  `numeroLancamento` BIGINT NOT NULL,
  `idPessoaRegistrouLancamento` BIGINT NULL,
  `isDespesa` TINYINT(1) NOT NULL,
  `descricao` VARCHAR(60) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `valorJuros` DECIMAL(10,2) NULL,
  `dataVencimento` DATE NULL,
  `dataPagamento` BIGINT NULL,
  `emitente` VARCHAR(45) NULL,
  `isParcelado` TINYINT(1) NOT NULL,
  `observacao` TEXT NULL,
  `isPago` TINYINT(1) NOT NULL,
  `dataRegistro` DATETIME NOT NULL,
  `idEvento` INT NULL,
  PRIMARY KEY (`idLancamento`),
  INDEX `fk_lancamento_paroquiano1_idx` (`idPessoaRegistrouLancamento` ASC),
  INDEX `fk_lancamento_evento1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_lancamento_paroquiano1`
    FOREIGN KEY (`idPessoaRegistrouLancamento`)
    REFERENCES `SGPARCAT`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `SGPARCAT`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`organismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`organismo` (
  `idOrganismo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idOrganismo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`membro` (
  `idPessoa` BIGINT NOT NULL,
  `idOrganismo` INT NOT NULL,
  `idFuncao` INT NOT NULL,
  PRIMARY KEY (`idPessoa`, `idOrganismo`),
  INDEX `fk_paroquiano_has_organismo_organismo1_idx` (`idOrganismo` ASC),
  INDEX `fk_paroquiano_has_organismo_paroquiano_idx` (`idPessoa` ASC),
  INDEX `fk_membro_funcao1_idx` (`idFuncao` ASC),
  CONSTRAINT `fk_paroquiano_has_organismo_paroquiano`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `SGPARCAT`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paroquiano_has_organismo_organismo1`
    FOREIGN KEY (`idOrganismo`)
    REFERENCES `SGPARCAT`.`organismo` (`idOrganismo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membro_funcao1`
    FOREIGN KEY (`idFuncao`)
    REFERENCES `SGPARCAT`.`funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`participante` (
  `idPessoa` BIGINT NOT NULL,
  `idEvento` INT NOT NULL,
  `idFuncao` INT NOT NULL,
  PRIMARY KEY (`idPessoa`, `idEvento`),
  INDEX `fk_paroquiano_has_evento_evento1_idx` (`idEvento` ASC),
  INDEX `fk_paroquiano_has_evento_paroquiano1_idx` (`idPessoa` ASC),
  INDEX `fk_parcipante_funcao1_idx` (`idFuncao` ASC),
  CONSTRAINT `fk_paroquiano_has_evento_paroquiano1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `SGPARCAT`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paroquiano_has_evento_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `SGPARCAT`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcipante_funcao1`
    FOREIGN KEY (`idFuncao`)
    REFERENCES `SGPARCAT`.`funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGPARCAT`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGPARCAT`.`endereco` (
  `idEndereco` BIGINT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `complemento` VARCHAR(60) NULL,
  `idPessoa` BIGINT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_endereco_pessoa1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `SGPARCAT`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
